### ISSUE TITLE
i dont even know

### ISSUE THREAD

**Issue by authenyoo** [7x11x13/free-bandcamp-downloader#2]
i try to download an album and it gives me this error
`Traceback (most recent call last):
  File "/home/authen/.local/bin/bcdl-free", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/authen/.local/pipx/venvs/free-bandcamp-downloader/lib/python3.11/site-packages/free_bandcamp_downloader/main.py", line 338, in main
    driver = get_driver()
             ^^^^^^^^^^^^
  File "/home/authen/.local/pipx/venvs/free-bandcamp-downloader/lib/python3.11/site-packages/free_bandcamp_downloader/main.py", line 121, in get_driver
    driver = webdriver.Firefox(
             ^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got an unexpected keyword argument 'firefox_options'`
i have the gecko driver and its on /usr/local/bin

**Comment by 7x11x13** [comment]
Can you try again with the latest version? Selenium is no longer needed
