### ISSUE TITLE
Invalid URL returning 'None'?

### ISSUE THREAD

**Issue by alt44s** [7x11x13/free-bandcamp-downloader#4]
Issue when attempting to download the whole Lost Frog Productions label. It'd be nice if there was an option to skip error'd downloads as well.

`INFO:free_bandcamp_downloader:Downloading https://lostfrog.bandcamp.com/album/--9
INFO:free_bandcamp_downloader:https://lostfrog.bandcamp.com/album/--9 does not require email
Traceback (most recent call last):
  File "D:\Users\my_username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Users\my_username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Users\my_username\AppData\Local\Programs\Python\Python310\Scripts\bcdl-free.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Users\my_username\AppData\Local\Programs\Python\Python310\lib\site-packages\free_bandcamp_downloader\__main__.py", line 405, in main
    downloader.download_label(arguments["-l"], arguments["--force"])
  File "D:\Users\my_username\AppData\Local\Programs\Python\Python310\lib\site-packages\free_bandcamp_downloader\__main__.py", line 273, in download_label
    self.download_album(album_link, force)
  File "D:\Users\my_username\AppData\Local\Programs\Python\Python310\lib\site-packages\free_bandcamp_downloader\__main__.py", line 259, in download_album
    self._download_file(
  File "D:\Users\my_username\AppData\Local\Programs\Python\Python310\lib\site-packages\free_bandcamp_downloader\__main__.py", line 137, in _download_file
    r = self.session.get(download_page_url)
  File "D:\Users\my_username\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\Users\my_username\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Users\my_username\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "D:\Users\my_username\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Users\my_username\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?`

**Comment by 7x11x13** [comment]
Didn't know that "trackless" albums were a thing on Bandcamp! Should be fixed in v0.1.5
